/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Marius.Eder (https://sketchfab.com/Marius.Eder)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/glasses-007651a9450746a5b6c5a126d484cd52
Title: Glasses
*/
"use client"
import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from "@react-three/fiber"

export default function Sprite(props) {
  const { nodes, materials } = useGLTF('./models/glasses-transformed.glb');

  const modelRef = useRef()

  useFrame((state, delta, xrFrame) => {
    console.log(state.clock)
    modelRef.current.position.y = Math.sin(state.clock.elapsedTime) * 0.15
  })

  return (
    <group {...props} dispose={null}
      ref={modelRef}
      position={[-0.325, 0, 0]}
      scale={[1.55, 1.5, 1.5]}
      rotation={[0.15, -0.55, 0]}
    >
      <mesh castShadow receiveShadow geometry={nodes.mesh_0.geometry} material={materials.Frame} />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_1.geometry}
        material={materials.Handles}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_2.geometry}
        material={materials['Frame.1']}
      />
    </group>
  )
}

useGLTF.preload('./models/glasses-transformed.glb')
